### ISSUE TITLE
Improve callback syntax

### ISSUE THREAD

**Issue by jedahan** [jedahan/living-room-js#2]
From @cursiv, a syntax that feels nice
```javascript
let pageId = 'foo'
let [ claimer, activeText ] = await findStatementValues`${_} claims ${pageId} has active text ${_}.`
console.log(claimer, activeText)
```

Given a set of messages
```javascript
say(`gorog is a barbarian`)
say(`gorog is at 10, 20`)
let class = `barbarian`
```

what would a multiselect look like?
```js
let [ name, _, name, x, y] = await recall `${_} is a ${class}`, `${_} is at ${_}, ${_}`
```

hmm, seems we cannot bind. We could provide for:
```js
let [ name, _, x, y] = await recall `${name} is a ${class}`, `${name} is at ${_}, ${_}`
```

but now this confuses interpolation with binding

how about removing {} for destructuring?

```js
let [ name, x, y ] = await recall `$name is a ${class}`, `$name is at $_, $_`
```

Well there is some ambiguity here - there is nothing special about the name array on the left and the binding on the right. If we want back to the original destructuring, would this even work?

```js
let {name, [ x, y ]} = await recall `$name is a ${class}`, `$name is at $_, $_`
```

What if, when binding multiple variables, we automatically made the returned value an array with each of those values in order?

```js
let { name, _: [x, y] } = await recall `$name is a ${class}`, `$name is at $_, $_`
```

This makes `_` no longer special, and allows for adding some more semantics:

```js
let { name, pos: [x, y] } = await recall `$name is a ${class}`, `$name is at $pos, $pos`
```

Downside here is we are less succinct, also, how do we resolve:
```js
let { name, pos: [x, y] } = await recall `$name is a ${class}`, `$name daughter of $name is at $pos, $pos`
```
does name return an array? how do we do binding?

```js
// - longer
// + more explicit
// - bindings can auto-arrayize
// - no solution for bindings once in a select, and twice in another select
let { name, pos: [x, y] } = await recall `$name is a ${class}`, `$name is at $pos, $pos`

// + shorter
// + less strict
// - $_ is special
let [ name, x, y ] = await recall `$name is a ${class}`, `$name daughter of $name is at $_, $_`
```

Any other ideas? (Also, would `$$` look/feel better than `$_`? which captures best the idea of a hole or wildcard?)

```js
let [ name, x, y ] = await recall `$name is a ${class}`, `$name daughter of $name is at $_, $_`
```

**Comment by cursiv** [comment]
Another idea:

```js
let character = `barbarian`
let { name, x, y } = await recall `$name is a ${character}` `$name is at $x, $y` ()
```

All identical variable names are binded. So

```js
recall `$name is a ${character}` `$name daughter of $name is at $pos, $pos` ()
```

means parent and daughter must have the same name and x and y must be equal.

**Comment by jedahan** [comment]
I like that a lot. The only question it leaves open: should we support wildcards explicitly, to allow for people to just say 'i dont care what this binds to / dont bind this', or just say 'bind to $a, $b, $c and just don't use them?'

**Comment by cursiv** [comment]
Wildcards can make it harder to infer the meaning or structure of a message. I don't think we should support wildcards explicitly unless there is at least a demonstrated need for them.

**Comment by jedahan** [comment]
We know have room.{assert,retract,select} return a promise, so we get regular destructuring :)
